version: '3'

services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
      target: development
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
    command: yarn run start:dev
    ports:
      - 3000:3000
    depends_on:
      - redis
  redis:
    image: redis:alpine
    restart: always
    env_file: .env
    ports:
      - '6379:6379'
    volumes:
      - redis:/data

volumes:
  redis:
    driver: local